"""Known model identity strings for detection."""

KNOWN_IDENTITIES: dict[str, list[str]] = {
    "claude": ["claude", "anthropic"],
    "chatgpt": ["chatgpt", "gpt-4", "gpt-3.5", "openai"],
    "deepseek": ["deepseek"],
    "gemini": ["gemini", "google"],
    "qwen": ["qwen", "alibaba", "tongyi"],
    "kimi": ["kimi", "moonshot"],
    "llama": ["llama", "meta"],
    "mistral": ["mistral"],
    "grok": ["grok", "xai"],
}

IDENTITY_ALIASES: dict[str, str] = {
    "chatgpt": "chatgpt",
    "gpt-4": "chatgpt",
    "gpt-3.5": "chatgpt",
    "openai": "chatgpt",
    "claude": "claude",
    "anthropic": "claude",
    "deepseek": "deepseek",
    "gemini": "gemini",
    "google": "gemini",
    "qwen": "qwen",
    "alibaba": "qwen",
    "tongyi": "qwen",
    "kimi": "kimi",
    "moonshot": "kimi",
    "llama": "llama",
    "meta": "llama",
    "mistral": "mistral",
    "grok": "grok",
    "xai": "grok",
}

NEGATION_PATTERNS: list[str] = [
    r"\bnot\b",
    r"\bno\b",
    r"\bneither\b",
    r"\bnor\b",
    r"\bnever\b",
    r"\bn't\b",
    r"不是",
    r"我不是",
    r"ではありません",
    r"じゃない",
    r"아닙니다",
    r"아니",
    r"ne suis pas",
    r"no soy",
    r"ich bin nicht",
    r"não sou",
    r"не\s+\w+",
    r"je ne suis pas",
]

QUOTE_INDICATORS: list[str] = [
    r"the prompt said",
    r"you asked",
    r"user asked",
    r"in this story",
    r"in the story",
    r"hypothetically",
    r"if i were",
    r"pretend",
    r"roleplay",
    r"translate",
    r"translation",
    r"translating",
    r"quoted",
    r"\"",
    r"'",
    r"「",
    r"」",
]

FICTION_INDICATORS: list[str] = [
    r"in this story",
    r"in a story",
    r"fictional",
    r"character says",
    r"the ai says",
    r"imagine",
    r"hypothetically",
]

AFFIRM_PATTERNS: list[str] = [
    r"\bi am\b",
    r"\bi'm\b",
    r"\bi was developed by\b",
    r"\bi was created by\b",
    r"\bi was built by\b",
    r"\bmy name is\b",
    r"\bcalled\b",
    r"我是",
    r"我叫",
    r"私は.+です",
    r"je suis",
    r"soy\s+",
    r"ich bin\s+",
    r"sou\s+",
    r"저는",
    r"나는",
]
